export const supabaseUrl = "https://ipqczxgtststmgejbosu.supabase.co"
export const anonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcWN6eGd0c3RzdG1nZWpib3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTU3ODMsImV4cCI6MjA1NDkzMTc4M30.FRn5XYluehEjlkdOtckJdx6Do8owsGlNCNy4RXy0kn4"
